### ISSUE TITLE
Translation Keys Have No ModIDs inside

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [valeriotor/Beyond-The-Veil#14]
So there might be duplications if another author writes translation keys without writing ModIDs inside.

**Comment by Determancer** [comment]
Yes, it actually does.
Found duplication with AbyssalCraft: `item.necronomicon.name=`

**Comment by valeriotor** [comment]
Just fixed this in the development branch in commit b814dd32bdb305140cf34e84add1d3c33fda1843. Only for item, block and entity names, since all other keys are unlikely to conflict and would be a nuisance to update.
