### ISSUE TITLE
Dweller Dialog Problem

### ISSUE THREAD

**Issue by Determancer** [valeriotor/Beyond-The-Veil#17]
There is something wrong with the dialog of a type of dwellers(maybe the "miner"?)

![dweller dialogue issue](https://user-images.githubusercontent.com/49300241/95942776-a8dc2080-0e16-11eb-8bac-ee5056159368.png)

**Comment by valeriotor** [comment]
Yeah, the miner is actually an unused variant of Hamlet Dweller. I added its profession and texture to the game but felt too lazy to give him a structure to spawn him, so he just sits there spewing nonsense, and will never spawn naturally.
