### ISSUE TITLE
Dream Focus: Fluid Route Setting Process Cannot Stop

### ISSUE THREAD

**Issue by Determancer** [valeriotor/Beyond-The-Veil#20]
When there is a block directly at the bottom of the Dream Focus: Fluid, and then using the Focus to set the route, the process will continue even after the timer has already been counted down. 
So far as I know, the only way to stop the process is to interact with other devices (such as Dream Foucus: Villager and Dream Foucus: Item).

**Comment by valeriotor** [comment]
Some people had been reporting an "infinite pathing" bug for Dream Foci and I couldn't figure out how to reproduce it, so I am **extremely** thankful for this. Just fixed it in [this commit](https://github.com/valeriotor/Beyond-The-Veil/commit/4c7f07fe4c94704cd2e9d85f5fb8c9b6a7b15ff6) of the development branch, I'll close the issue once I release the update.
