### ISSUE TITLE
Tablet Research Entry Text Lost

### ISSUE THREAD

**Issue by Determancer** [valeriotor/Beyond-The-Veil#24]
As the picture shows, the original key is at the bottom of the tablet research entry screen.
Currently, there is no research.inscription_complete.text in .lang files.
If I manually add this line into .lang file, it will work. But I don't know what should be the original text.
![2020-10-27_23 41 49 (1)](https://user-images.githubusercontent.com/49300241/97326568-170cf280-18af-11eb-95a4-585c3c396dd2.jpg)

**Comment by valeriotor** [comment]
This will be fixed in the next update. In the meantime, the text should be "Decipher a tablet".
