### ISSUE TITLE
First Person Viewport is fixed at human height

### ISSUE THREAD

**Issue by m-vlad** [valeriotor/Beyond-The-Veil#3]
Hey there, this doesn't have a crash log, it doesn't even show up in the Latest log. When I have BTV installed the first person camera is fixed at player-level. This wouldn't be an issue if I wasn't using something like Changeling to change into different creatures. This doesn't happen with BTV installed.

**Comment by valeriotor** [comment]
Thanks, that was the result of me doing something really stupid :(
Should be fixed now, version 1.1.2 is up on Curseforge.

**Comment by m-vlad** [comment]
Damn that's a fast update, thanks for fixing it so fast!
