### ISSUE TITLE
Shoggoth Won't Calm Down

### ISSUE THREAD

**Issue by Determancer** [valeriotor/Beyond-The-Veil#37]
(Hopefully detailed description of the event will help)
I accidently released Shoggoth to build towers while forgetting about my poor sheep in the sheepfolder nearby. Shoggoth nearly killed them all, I tried my best to save some of them and move them to about 30 blocks away from the scene of carnage. However, Shoggoth has a long following range and ran to the rest of the sheep, so I quickly delievered the Shoggoth Map to it, it then turned back to the work.
After finishing the building, it appears to be clam down, staying at its place. But when I attempted to use my Blackjack to retrieve it, I failed again and again. I tried to quit the world and relogined, but this didn't help. Finally I had to kill the Shoggoth and made a new one.
It seemed like something was wrong with the "calm mechanism". Shouldn't it be seen as calm when it has no trend to attack other mobs?

**Comment by valeriotor** [comment]
It's part of the same problem you described in Issue#23. Will be fixed in the next update.
