### ISSUE TITLE
Sudden Crash when going far from spawn

### ISSUE THREAD

**Issue by buratings** [valeriotor/Beyond-The-Veil#4]
When I left my base to gather supplies, a crash occurred. Initially, I thought that Minecraft Comes Alive mod was the problem, but after removing the mod the crash still persisted. This is the crash report:
[crash-2020-04-11_22.20.41-server.txt](https://github.com/valeriotor/Beyond-The-Veil/files/4464762/crash-2020-04-11_22.20.41-server.txt)

(Not native english speaker sorry.)

**Comment by valeriotor** [comment]
Hey there, thanks for the report! That problem has already been reported just a few days ago, and I've already fixed it, so you should try and get the latest version of the mod (v0.1.2 right now) and it should be fixed!
