### ISSUE TITLE
the sand texture should be modified

### ISSUE THREAD

**Issue by Zack7292** [valeriotor/Beyond-The-Veil#5]
Hi, i really like your mod in general, its really original and it generally look good. but there one texture i think fit badly when put next to the other because of a repetition felling and its the sand

![image](https://user-images.githubusercontent.com/45187146/79404697-6c5f6300-7f60-11ea-8501-5ff7fc67ea9a.png)

this screen show more directly the place where it happen on the sand

**Comment by valeriotor** [comment]
Oh no I can't unsee it..
Along with the falling floor issue, I think I'll just rework sand. Instead of retexturing I could try and make it like vanilla grass, which can have various orientations in its texture to prevent repetition.

**Comment by valeriotor** [comment]
![2020-04-16_12 04 57](https://user-images.githubusercontent.com/44274884/79443908-c00e9280-7fda-11ea-9bca-bfa64008cfbf.png)
Ok I did that and also changed the texture, might be better.

**Comment by valeriotor** [comment]
![2020-04-16_12 05 09](https://user-images.githubusercontent.com/44274884/79444000-d9174380-7fda-11ea-9021-6902ccadbfe9.png)
Nevermind.. gotta edit a bit more to prevent accidental swastikas.........

**Comment by Zack7292** [comment]
its definitely a lot better :)
