### ISSUE TITLE
missing floor

### ISSUE THREAD

**Issue by Zack7292** [valeriotor/Beyond-The-Veil#6]
maybe adding a floor to each and every building could be cool?
![Screenshot_218](https://user-images.githubusercontent.com/45187146/79408447-5b671f80-7f69-11ea-8a99-d8a5bf8021b5.png)

**Comment by valeriotor** [comment]
This problem has actually been bothering me for over an year. See, the buildings actually have floors, even 4-5 blocks deep, it's just that the sand falls down.. and I don't want them to do like vanilla villages where they keep adding blocks till they find a solid one. I think I'll just make the sand into a non falling block and be done with it.

**Comment by Zack7292** [comment]
maybe just making the structure generate sand cube under it until it touch the ground, i know a friend has done this with mcreator for not having flying trees, so doing a so should fix this

**Comment by Zack7292** [comment]
if you want a suggestion that will 100% fix this issue easily, adding stars to enter them so it go on a floor (like in vanilla villages) :)

**Comment by valeriotor** [comment]
Just released v0.2, in the end I just decided to make Dark Sand a non falling block. Easiest way to go about it, and fixed all issues.
