### ISSUE TITLE
"Dreams of others" quest issue

### ISSUE THREAD

**Issue by Zack7292** [valeriotor/Beyond-The-Veil#8]
in this quest, it seem like i actually need to be in another player, but i don't want to play in multiplayer, so maybe making it work either with villager or adding a mob that would work with it could make this quest work better?

**Comment by valeriotor** [comment]
While there are features in the mod that can only be used in multiplayer, it is never required to progress through the mod.
For the Dreams of Others quest the Player only needs to initiate a trade with a villager. While the Human Memory will have no effect in singleplayer, you only need to unlock it, not use it, to progress through Al Azif.
If you're stuck at the Dreams of Void research not unlocking, I suggest you look at the very last line in the Plunging Down research ;)
